# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nocode startup
name: "Nocode startup"
email: info@nocode-startup.com
meta_description: "Nocode startupはプログラミングの知識ゼロで、既存のWebサービスを使ってスタートアップのMVPを作る方法や、副業を手軽かつ簡単にスタートする方法を紹介するブログです。"
description: >- # this means to ignore newlines until "baseurl:"
  Nocode startupはプログラミングの知識ゼロで、既存のWebサービスを使ってスタートアップのMVPを作る方法や、副業を手軽かつ簡単にスタートする方法を紹介するブログです。
baseurl:  # the subpath of your site, e.g. /blog
url: https://www.nocode-startup.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tsureezy
github_username:  tatjapan
google_analytics: 
disqus: 'nocode-startup'
mailchimp-list:

# Authors
authors:
  Tatsuya:
    name: Tatsuya
    display_name: Tatsuya
    gravatar: c34d3fad7f6e7d1f5a5014baa942880a
    email: tatsuya.tsuri@gmail.com
    web: https://www.nocode-startup.cpm
    twitter: https://twitter.com/tsureezy
    description: "当ブログ管理人。フリーランスWebエンジニア。ゼロからプログラミングを習得してWebアプリを作成した際の失敗談から得た教訓や、これからアプリを作成して起業する人に向けたアドバイス等々書いていきます。"

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

paginate: 6
paginate_path: "/blog/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
